---
apiVersion: v1
kind: Service
metadata:
  name: db-covid-redis-service
  labels:
    username: ewang
    env: covid-19
spec:
  type: ClusterIP
  selector:
    app: db-covid-19-redis
  ports:
  - name: db-covid-redis
    port: 6379
    targetPort: 6379