---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: covid-pvc-data
  labels:
    username: ewang
    env: covid-19
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi