---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewang-test-redis-deployment
  labels:
    app: db-covid-19-redis
    username: ewang
    env: covid-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-covid-19-redis
  template:
    metadata:
      labels:
        app: db-covid-19-redis
        username: ewang
        env: covid-19
    spec:
      containers:
        - name: covid-19-redis
          imagePullPolicy: Always
          image: redis:5.0.0
          volumeMounts:
          - name: covid-pvc-data
            mountPath: "/data"
      volumes:
      - name: covid-pvc-data
        persistentVolumeClaim:
          claimName: covid-pvc-data