---
apiVersion: v1
kind: Service
metadata:
  name: ewang-test-redis-service
  labels:
    username: ewang
    env: test
spec:
  type: ClusterIP
  selector:
    app: ewang-test-redis
  ports:
  - name: hello-test-redis
    port: 6379
    targetPort: 6379