---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-covid-flask-deployment
  labels:
    app: api-covid-flask
    username: ewang
    env: covid-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-covid-flask
  template:
    metadata:
      labels:
        app: api-covid-flask
        username: ewang
        env: covid-19
    spec:
      containers:
        - name: api-covid-flask
          imagePullPolicy: Always
          image: cobcannon123/covid19_data:latest
          command: ["python3", "api.py"]
          #command: ["sleep", "9999999999"]
          env:
          - name: FLASK_APP
            value: "api.py"
          ports:
          - name: http
            containerPort: 5000