---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-covid-deployment
  labels:
    app: worker-covid-deployment
    username: ewang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-covid-deployment
  template:
    metadata:
      labels:
        app: worker-covid-deployment
        username: ewang
    spec:
      containers:
        - name: worker-covid-deployment
          imagePullPolicy: Always
          image: cobcannon123/covid19_data:latest
          command: ["python3", "worker.py"]
          #command: ["sleep", "9999999999"]
          env:
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_IP
              value: 10.99.12.229